name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.18.0'
      - name: Run test
        run: >
          make test
      - name: Run E2E test
        run: >
          go run main.go validate -f test/petstore.yaml
          go run main.go validate -f test/petstore.json